plugins { id 'com.android.application' }

android {
    namespace 'dev.aurora.tv'
    compileSdk 35
    defaultConfig {
        applicationId 'dev.aurora.tv'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.5.0'
        testInstrumentationRunner 'dev.aurora.tv.RegressionInstrumentation'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
